package Intergiciels.tp_spring.Controllers;

import Intergiciels.tp_spring.Entities.League;
import Intergiciels.tp_spring.Entities.Role;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import Intergiciels.tp_spring.Entities.User;
import Intergiciels.tp_spring.Repositories.UserRepository;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    @GetMapping("/add")
    public String userForm(Model model) {
        model.addAttribute("user", new User());
        return "registration";
    }

    @PostMapping(path="/add") // Map ONLY GET Requests
    public String addNewUser (@ModelAttribute User user) {
        user.setEnabled(true);
        user.setPersonnages();
        user.setPoints(10000);
        user.setRole(Role.ROLE_USER);
        user.setLeague(League.Bronze);
        userRepository.save(user);
        return "login";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping("/logout")
    public String logout(Model model) {
        return "login";
    }
}

