package Intergiciels.tp_spring.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import Intergiciels.tp_spring.Entities.User;
import Intergiciels.tp_spring.Repositories.UserRepository;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    @GetMapping("/add")
    public String userForm(Model model) {
        model.addAttribute("user", new User());
        return "index";
    }

    @PostMapping(path="/add") // Map ONLY GET Requests
/*    public @ResponseBody String addNewUser (@RequestParam String name,
                                            @RequestParam String first_name,
                                            @RequestParam String email,
                                            @RequestParam String username,
                                            @RequestParam String password
                                            ) {

        //name=morin&first_name=valentin&email=vmorin@gmail.com&username=vahflouz&password=password

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        n.setFirst_name(first_name);
        n.setUsername(username);
        n.setPassword(password);
        n.setId(1);
        n.setEnabled(true);
        n.setPersonnages();
        userRepository.save(n);
        return "Saved";
    }*/

    public @ResponseBody String addNewUser (@ModelAttribute User user) {

        //name=morin&first_name=valentin&email=vmorin@gmail.com&username=vahflouz&password=password

        user.setEnabled(true);
        user.setPersonnages();
        userRepository.save(user);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}

